
language: haskell

cache:
  directories:
  - $HOME/.stack/

# Download and install Stack executable
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar -xzO --wildcards '*/stack' > ~/.local/bin/stack
  - chmod a+x ~/.local/bin/stack

install:
  - stack setup

script:
  - stack build --fast

after_success:
  - cd $TRAVIS_BUILD_DIR
  - ./scripts/deploy
