# Missing an organization? Ensure Heroku Dashboard has organization access.

resolver: lts-6.1
flags: {}
#extra-deps:
#  - hakyll-4.8.3.2
#  - snap-core-0.9.8.0
#  - snap-server-0.9.5.1
#  - MonadCatchIO-transformers-0.3.1.3
#  - attoparsec-enumerator-0.3.4
#  - blaze-builder-enumerator-0.2.1.0
#  - bytestring-mmap-0.2.2
#  - enumerator-0.4.20
#  - zlib-enum-0.2.3.1
